#!/bin/bash

# This is script that creates and downloads skeleton
# Flask application from https://github.com/kristjanstrojan/flaskstack.

echo "Name of application folder: "
read app_folder
mkdir $app_folder
cd $app_folder
wget https://github.com/kristjanstrojan/flaskstack/archive/master.zip
unzip ./master.zip
rm ./master.zip
cp -r flaskstack-master/* ./
rm -r flaskstack-master

